name: secret-check
on: push
jobs:
  secret-check:
    runs-on: ubuntu-latest
    steps:
      - name: secret check fetch
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          if [ -n APP_TOKEN" ]; then
            echo "token is available for this step"
          fi
